[asusctl-latest]
src.aur = 'asusctl'
# src.manual = '4.5.1'
fetch.git = 'https://gitlab.com/asus-linux/asusctl'
cargo_locks = [ 'Cargo.lock' ]

[droidcam-obs-plugin]
src.github_tag = 'dev47apps/droidcam-obs-plugin'
fetch.url = 'https://github.com/dev47apps/droidcam-obs-plugin/releases/download/$ver/droidcam_obs_$ver_linux.zip'

[fcitx5-nord]
src.git = 'https://github.com/tonyfettes/fcitx5-nord.git'
fetch.github = 'tonyfettes/fcitx5-nord'

[fcitx5-skk]
src.github_tag = 'fcitx/fcitx5-skk'
fetch.github = 'fcitx/fcitx5-skk'

[juce]
src.github_tag = 'juce-framework/JUCE'
fetch.github = 'juce-framework/JUCE'

[knp]
src.git = 'https://github.com/ku-nlp/knp/'
fetch.github = 'ku-nlp/knp'

[notify-rust]
src.git = 'https://github.com/flukejones/notify-rust.git'
fetch.github = 'flukejones/notify-rust'

[skk-emoji-jisyo]
src.github_tag = 'uasi/skk-emoji-jisyo'
fetch.github = 'uasi/skk-emoji-jisyo'

[jawiki-kana-kanji-dict]
src.git = 'https://github.com/tokuhirom/jawiki-kana-kanji-dict.git'
fetch.url = 'https://raw.githubusercontent.com/tokuhirom/jawiki-kana-kanji-dict/$ver/SKK-JISYO.jawiki'

[snack]
src.webpage = 'https://www.speech.kth.se/snack/'
src.regex = 'Snack v[0-9]+\.[0-9]+\.[0-9]+'
src.prefix = 'Snack v'
fetch.url = 'http://www.speech.kth.se/snack/dist/snack$ver.tar.gz'

[supergfxctl-latest]
src.aur = 'supergfxctl'
fetch.git = 'https://gitlab.com/asus-linux/supergfxctl'
cargo_locks = [ 'Cargo.lock' ]

[yaskkserv2]
src.github_tag = 'wachikun/yaskkserv2'
fetch.github = 'wachikun/yaskkserv2'
cargo_locks = [ 'Cargo.lock' ]

[wavesurfer]
src.httpheader = 'http://downloads.sourceforge.net/wavesurfer/wavesurfer-1.8.8p5-src.tgz'
src.regex = '[0-9]+.[0-9]+.[0-9]+p[0-9]+'
fetch.url = 'http://downloads.sourceforge.net/wavesurfer/wavesurfer-$ver-src.tgz'

[xp-pen-tablet]
src.aur = 'xp-pen-tablet'
fetch.url = 'https://www.xp-pen.com/download/file/id/1936/pid/690/ext/gz.html'

[unityhub-latest]
src.aur = 'unityhub'
fetch.url = 'https://hub.unity3d.com/linux/repos/deb/pool/main/u/unity/unityhub_amd64/unityhub-amd64-$ver.deb'

# python modules
[doq]
src.pypi = 'doq'
fetch.pypi = 'doq'

[pyknp]
src.pypi = 'pyknp'
fetch.pypi = 'pyknp'

