name: build check
on: [push, pull_request, workflow_call]

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Cache nvfetcher
        uses: actions/cache@v3.2.6
        with:
          path: ~/.local/share/nvfetcher
          key: ${{ runner.os }}-nvfetcher
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: misumisumi
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Run flake check
        run: nix flake check