name: build check
on:
  pull_request:

permissions: read-all
jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      change: ${{ steps.change.outputs.nix }}
    steps:
      - uses: dorny/paths-filter@v3
        id: change
        with:
          filters: |
            nix:
              - "**.nix"
              - "flake.lock"

  build-check:
    runs-on: ubuntu-latest
    needs:
      - check-paths
    if: needs.check-paths.outputs.change == 'true'
    steps:
      - uses: dorny/paths-filter@v3
        id: change
        with:
          filters: |
            nix:
              - "**.nix"
              - "flake.lock"

      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          build-mount-path: "/nix/store"
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v14
        with:
          name: misumisumi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      - name: Build check
        run: nix run github:Mic92/nix-fast-build  -- --no-link
