name: Push to cachix
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          build-mount-path: "/nix/store"
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - uses: actions/checkout@v4

      - name: Cache nvfetcher
        uses: actions/cache@v4
        with:
          path: ~/.local/share/nvfetcher
          key: ${{ runner.os }}-nvfetcher

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v14
        with:
          name: misumisumi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run flake build
        run: nix run github:Mic92/nix-fast-build  -- --no-link
