name: update repository
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 18 * * 5" # runs weekly on Saturday at 03:00 (JST)

permissions: read-all
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/update-flake-lock@v21
        id: update
        with:
          token: ${{ github.token }}
          commit-msg: "chore(flake.lock): auto update flake.lock"
          pr-title: "chore(flake.lock): auto update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated

  update-readme:
    runs-on: ubuntu-latest
    needs: update-repo
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: "update_flake_lock_action"
          token: ${{ steps.generate-token.outputs.token }}

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update README
        run: |
          ./scripts/update-readme.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(README): auto update README"
          skip_fetch: true
          file_pattern: "README.md"
